
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ethan - God Tier
 */
public class CompareSupplierProducts extends javax.swing.JFrame {

    /**
     * Creates new form ViewSupplierProducts
     */
    private ArrayList<String> prod_names;
    private ArrayList<Product> prods;
    public CompareSupplierProducts() {
        prods = new ArrayList<>();
        prods.add(new Product("0001", "Foam Roller", "Cylinder made of foam for massaging the body", 2, 4.5, 2.5, 24, 25, "Massage", "Boston Fitness Supplies"));
        prods.add(new Product("0002", "Foam Roller", "Cylinder made of foam for massaging the body", 1.8, 4, 3, 18, 18, "Massage", "Winter Gear Distributers"));
        prods.add(new Product("0003", "5lb Dumbbell", "5lb neoprene dumbbell", 5, 2.76, 2.5, 7.33, 15, "Weights", "Winter Gear Distributers"));
        prods.add(new Product("0004", "5lb Dumbbell", "5lb neoprene dumbbell", 5, 2.76, 2.75, 7.5, 13, "Weights", "Boston Fitness Supplies"));
        prods.add(new Product("0005", "Resistance bands", "Set of 5 resistance bands", 0.25, 0.3, 2.5, 12, 11.89, "Resistance Bands", "Boston Fitness Supplies"));
        prods.add(new Product("0006", "Resistance bands", "Set of 3 resistance bands", 0.25, 0.3, 2.5, 12, 7.99, "Resistance Bands", "Winter Gear Distributers"));
        prod_names = new ArrayList<>();
        prod_names.add("Foam Roller");
        prod_names.add("5lb Dumbbell");
        prod_names.add("Resistance Bands");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prod_list = new javax.swing.JList(prod_names.toArray());
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        left_supplier = new javax.swing.JTextField();
        left_id = new javax.swing.JTextField();
        left_product = new javax.swing.JTextField();
        left_weight = new javax.swing.JTextField();
        left_height = new javax.swing.JTextField();
        left_width = new javax.swing.JTextField();
        left_length = new javax.swing.JTextField();
        left_price = new javax.swing.JTextField();
        left_category = new javax.swing.JTextField();
        right_supplier = new javax.swing.JTextField();
        right_id = new javax.swing.JTextField();
        right_product = new javax.swing.JTextField();
        right_description = new javax.swing.JTextField();
        right_weight = new javax.swing.JTextField();
        right_height = new javax.swing.JTextField();
        right_width = new javax.swing.JTextField();
        right_length = new javax.swing.JTextField();
        right_price = new javax.swing.JTextField();
        right_category = new javax.swing.JTextField();
        left_description = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        prod_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prod_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prod_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prod_list);

        jLabel1.setText("Product ID");

        jLabel2.setText("Product");

        jLabel3.setText("Description");

        jLabel4.setText("Weight");

        jLabel5.setText("Height");

        jLabel6.setText("Width");

        jLabel7.setText("Length");

        jLabel8.setText("Price");

        jLabel9.setText("Category");

        jLabel10.setText("Supplier");

        jLabel11.setText("Product ID");

        jLabel12.setText("Product");

        jLabel13.setText("Description");

        jLabel14.setText("Weight");

        jLabel15.setText("Height");

        jLabel16.setText("Width");

        jLabel17.setText("Length");

        jLabel18.setText("Price");

        jLabel19.setText("Supplier");

        jLabel20.setText("Category");

        left_supplier.setEditable(false);
        left_supplier.setColumns(1);

        left_id.setEditable(false);
        left_id.setColumns(1);

        left_product.setEditable(false);
        left_product.setColumns(1);

        left_weight.setEditable(false);
        left_weight.setColumns(1);

        left_height.setEditable(false);
        left_height.setColumns(1);

        left_width.setEditable(false);
        left_width.setColumns(1);

        left_length.setEditable(false);
        left_length.setColumns(1);

        left_price.setEditable(false);
        left_price.setColumns(1);

        left_category.setEditable(false);
        left_category.setColumns(1);

        right_supplier.setEditable(false);
        right_supplier.setColumns(1);

        right_id.setEditable(false);
        right_id.setColumns(1);

        right_product.setEditable(false);
        right_product.setColumns(1);

        right_description.setEditable(false);
        right_description.setColumns(1);

        right_weight.setEditable(false);
        right_weight.setColumns(1);

        right_height.setEditable(false);
        right_height.setColumns(1);

        right_width.setEditable(false);
        right_width.setColumns(1);

        right_length.setEditable(false);
        right_length.setColumns(1);

        right_price.setEditable(false);
        right_price.setColumns(1);

        right_category.setEditable(false);
        right_category.setColumns(1);

        left_description.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(left_supplier)
                    .addComponent(left_id)
                    .addComponent(left_width)
                    .addComponent(left_height)
                    .addComponent(left_weight)
                    .addComponent(left_product)
                    .addComponent(left_description)
                    .addComponent(left_length)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(left_price, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(left_category))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(right_length, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(right_price, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_width, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_height, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_weight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_category, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_description, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_product, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_id)
                    .addComponent(right_supplier))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(left_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(right_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(left_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(left_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(left_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(left_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(left_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(left_length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(left_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(left_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(right_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(right_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(right_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(right_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(right_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(right_width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(right_length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(right_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(right_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(left_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prod_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prod_listMouseClicked
        if (prod_list.getSelectedValue().equalsIgnoreCase("5lb Dumbbell")){
            Product l = prods.get(2);
            left_supplier.setText(l.getSupplier());
            left_id.setText(l.getId());
            left_product.setText(l.getName());
            left_description.setText(l.getDescription());
            left_weight.setText("" + l.getWeight());
            left_height.setText("" + l.getHeight());
            left_width.setText("" + l.getWidth());
            left_length.setText("" + l.getLength());
            left_price.setText("$" + l.getPrice());
            left_category.setText(l.getCategory());
            
            Product r = prods.get(3);
            right_supplier.setText(r.getSupplier());
            right_id.setText(r.getId());
            right_product.setText(r.getName());
            right_description.setText(r.getDescription());
            right_weight.setText("" + r.getWeight());
            right_height.setText("" + r.getHeight());
            right_width.setText("" + r.getWidth());
            right_length.setText("" + r.getLength());
            right_price.setText("$" + r.getPrice());
            right_category.setText(r.getCategory());
        } else if(prod_list.getSelectedValue().equalsIgnoreCase("Foam Roller")){
            Product l = prods.get(0);
            left_supplier.setText(l.getSupplier());
            left_id.setText(l.getId());
            left_product.setText(l.getName());
            left_description.setText(l.getDescription());
            left_weight.setText("" + l.getWeight());
            left_height.setText("" + l.getHeight());
            left_width.setText("" + l.getWidth());
            left_length.setText("" + l.getLength());
            left_price.setText("$" + l.getPrice());
            left_category.setText(l.getCategory());
            
            Product r = prods.get(1);
            right_supplier.setText(r.getSupplier());
            right_id.setText(r.getId());
            right_product.setText(r.getName());
            right_description.setText(r.getDescription());
            right_weight.setText("" + r.getWeight());
            right_height.setText("" + r.getHeight());
            right_width.setText("" + r.getWidth());
            right_length.setText("" + r.getLength());
            right_price.setText("$" + r.getPrice());
            right_category.setText(r.getCategory());
        } else if(prod_list.getSelectedValue().equalsIgnoreCase("Resistance Bands")){
            Product l = prods.get(4);
            left_supplier.setText(l.getSupplier());
            left_id.setText(l.getId());
            left_product.setText(l.getName());
            left_description.setText(l.getDescription());
            left_weight.setText("" + l.getWeight());
            left_height.setText("" + l.getHeight());
            left_width.setText("" + l.getWidth());
            left_length.setText("" + l.getLength());
            left_price.setText("$" + l.getPrice());
            left_category.setText(l.getCategory());
            
            Product r = prods.get(5);
            right_supplier.setText(r.getSupplier());
            right_id.setText(r.getId());
            right_product.setText(r.getName());
            right_description.setText(r.getDescription());
            right_weight.setText("" + r.getWeight());
            right_height.setText("" + r.getHeight());
            right_width.setText("" + r.getWidth());
            right_length.setText("" + r.getLength());
            right_price.setText("$" + r.getPrice());
            right_category.setText(r.getCategory());
        }
    }//GEN-LAST:event_prod_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompareSupplierProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompareSupplierProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompareSupplierProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompareSupplierProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompareSupplierProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField left_category;
    private javax.swing.JTextField left_description;
    private javax.swing.JTextField left_height;
    private javax.swing.JTextField left_id;
    private javax.swing.JTextField left_length;
    private javax.swing.JTextField left_price;
    private javax.swing.JTextField left_product;
    private javax.swing.JTextField left_supplier;
    private javax.swing.JTextField left_weight;
    private javax.swing.JTextField left_width;
    private javax.swing.JList<String> prod_list;
    private javax.swing.JTextField right_category;
    private javax.swing.JTextField right_description;
    private javax.swing.JTextField right_height;
    private javax.swing.JTextField right_id;
    private javax.swing.JTextField right_length;
    private javax.swing.JTextField right_price;
    private javax.swing.JTextField right_product;
    private javax.swing.JTextField right_supplier;
    private javax.swing.JTextField right_weight;
    private javax.swing.JTextField right_width;
    // End of variables declaration//GEN-END:variables
}
