
import java.util.ArrayList;

/**
 *
 * @author Ethan Emmons
 */
public class CustViewWarehouseStock extends javax.swing.JFrame {
    private class ProductStock{
        private Product p;
        private int stockVal;
        private int daysUntilArrive;
        public ProductStock(Product p){
            this.p = p;
            int stock = (int)(Math.random() * 30);
            this.stockVal = stock > 22 ? 0 : stock;
            this.daysUntilArrive = -1;
        }
        public Product getProductObj(){
            return this.p;
        }
        public int getNumStock(){
            return this.stockVal;
        }
        
        public int getNumDays(){
            return this.daysUntilArrive;
        }
        
        public void updateNumDays(){
            if (this.daysUntilArrive == -1){
                this.daysUntilArrive = (int) (Math.random() * 7) + 1;
            } else
                this.daysUntilArrive = (int) (Math.random() * 7) + 1;
        }
    }
    private Customer cust;
    private ArrayList<ProductStock> prods;
    private ArrayList<String> prod_names;
    public CustViewWarehouseStock(Customer cust) {
        prods = new ArrayList<>();
        prods.add(new ProductStock(new Product("0001", "Foam Roller", "Cylinder made of foam for massaging the body", 2, 4.5, 2.5, 24, 25, "Massage", "Boston Fitness Supplies")));
        prods.add(new ProductStock(new Product("0002", "Foam Roller", "Cylinder made of foam for massaging the body", 1.8, 4, 3, 18, 18, "Massage", "Winter Gear Distributers")));
        prods.add(new ProductStock(new Product("0003", "5lb Dumbbell", "5lb neoprene dumbbell", 5, 2.76, 2.75, 7.5, 13, "Weights", "Boston Fitness Supplies")));
        prods.add(new ProductStock(new Product("0004", "5lb Dumbbell", "5lb neoprene dumbbell", 5, 2.76, 2.5, 7.33, 15, "Weights", "Winter Gear Distributers")));
        prods.add(new ProductStock(new Product("0005", "Resistance Bands", "Set of 5 resistance bands", 0.25, 0.3, 2.5, 12, 11.89, "Resistance Bands", "Boston Fitness Supplies")));
        prods.add(new ProductStock(new Product("0006", "Resistance Bands", "Set of 3 resistance bands", 0.25, 0.3, 2.5, 12, 7.99, "Resistance Bands", "Winter Gear Distributers")));
        prod_names = new ArrayList<>();
        prod_names.add("0001");
        prod_names.add("0002");
        prod_names.add("0003");
        prod_names.add("0004");
        prod_names.add("0005");
        prod_names.add("0006");
        this.cust = cust;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prod_name_list = new javax.swing.JList(prod_names.toArray());
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        product_fld = new javax.swing.JTextField();
        supplier_fld = new javax.swing.JTextField();
        amount_in_stock_fld = new javax.swing.JTextField();
        order_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        prod_name_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prod_name_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prod_name_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prod_name_list);

        jLabel1.setText("Product:");

        jLabel2.setText("Supplier:");

        jLabel3.setText("Amount in Stock:");

        product_fld.setEditable(false);
        product_fld.setColumns(1);
        product_fld.setToolTipText("");

        supplier_fld.setEditable(false);
        supplier_fld.setColumns(1);
        supplier_fld.setToolTipText("");

        amount_in_stock_fld.setEditable(false);
        amount_in_stock_fld.setColumns(1);
        amount_in_stock_fld.setToolTipText("");

        order_btn.setText("Order Product");
        order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(product_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(supplier_fld, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amount_in_stock_fld, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(order_btn)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(product_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(supplier_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(amount_in_stock_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(order_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prod_name_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prod_name_listMouseClicked
        for (ProductStock ps : prods){
            if (prod_name_list.getSelectedValue().equalsIgnoreCase(ps.getProductObj().getId())){
                String in_stock = ps.getNumStock() == 0 ? "Out of stock" : "" + ps.getNumStock();
                amount_in_stock_fld.setText(in_stock);
                product_fld.setText(ps.getProductObj().getName());
                supplier_fld.setText(ps.getProductObj().getSupplier());
            }
        }
    }//GEN-LAST:event_prod_name_listMouseClicked

    private void order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btnActionPerformed
        for (ProductStock ps : prods){
            if (prod_name_list.getSelectedValue().equalsIgnoreCase(ps.getProductObj().getId())){
                System.out.println(ps.getNumStock());
                if (ps.getNumStock() == 0){
                    CustOrderConfirmation frame = new CustOrderConfirmation("Product is out of stock. Please select a different product.");
                    frame.setVisible(true);
                } else {
                    CustOrderConfirmation frame = new CustOrderConfirmation(String.format("Order number 000%d created", ((int)(Math.random() * 5) + 4)));
                    frame.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_order_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount_in_stock_fld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton order_btn;
    private javax.swing.JList<String> prod_name_list;
    private javax.swing.JTextField product_fld;
    private javax.swing.JTextField supplier_fld;
    // End of variables declaration//GEN-END:variables
}
