/*
 * @author Ethan Emmons
 */
public class ManagerMenu extends javax.swing.JFrame {
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_invoices_btn = new javax.swing.JButton();
        compare_supplier_products_btn = new javax.swing.JButton();
        compile_product_prices_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        view_invoices_btn.setText("View Invoices");
        view_invoices_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewinvoicebuttonpressed(evt);
            }
        });

        compare_supplier_products_btn.setText("Compare Supplier Products");
        compare_supplier_products_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compare_supplier_products_btnActionPerformed(evt);
            }
        });

        compile_product_prices_btn.setText("Compile Product Prices");
        compile_product_prices_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compile_product_prices_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(view_invoices_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compile_product_prices_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compare_supplier_products_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_invoices_btn)
                    .addComponent(compare_supplier_products_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compile_product_prices_btn)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewinvoicebuttonpressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewinvoicebuttonpressed
        ViewInvoices frame = new ViewInvoices();
        frame.setVisible(true);
    }//GEN-LAST:event_viewinvoicebuttonpressed

    private void compare_supplier_products_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compare_supplier_products_btnActionPerformed
        CompareSupplierProducts frame = new CompareSupplierProducts();
        frame.setVisible(true);
    }//GEN-LAST:event_compare_supplier_products_btnActionPerformed

    private void compile_product_prices_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compile_product_prices_btnActionPerformed
        CompileProductPrices frame = new CompileProductPrices();
        frame.setVisible(true);
    }//GEN-LAST:event_compile_product_prices_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compare_supplier_products_btn;
    private javax.swing.JButton compile_product_prices_btn;
    private javax.swing.JButton view_invoices_btn;
    // End of variables declaration//GEN-END:variables
}
