
import java.text.DecimalFormat;

/*
 * @author Ethan Emmons
 */
public class OnlineVsInstoreReport extends javax.swing.JFrame {
    private double l_rev;
    private double r_rev;
    private DecimalFormat formatter;
    public OnlineVsInstoreReport() {
        this.formatter = new DecimalFormat("#0.00");
        l_rev = (11000.0 + (Math.random() * ((50000.0 - 11000.0) + 1)));
        r_rev = (11000.0 + (Math.random() * ((50000.0 - 11000.0) + 1)));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        l_ord_placed_fld = new javax.swing.JTextField();
        l_ord_placed_fld.setText("" + (5 + (int)(Math.random() * ((25 - 5) + 1))));
        l_prod_sold_fld = new javax.swing.JTextField();
        l_prod_sold_fld.setText("" + (4 + (int)(Math.random() * ((14 - 4) + 1))));
        l_new_cust_fld = new javax.swing.JTextField();
        l_new_cust_fld.setText("" + (2 + (int)(Math.random() * ((6 - 2) + 1))));
        l_rev_fld = new javax.swing.JTextField();
        l_rev_fld.setText("" + formatter.format(l_rev));
        l_prof_fld = new javax.swing.JTextField();
        l_prof_fld.setText("" + formatter.format(l_rev - (2500 + (Math.random() * ((8000 - 2500 ) + 1)))));
        r_ord_placed_fld = new javax.swing.JTextField();
        r_ord_placed_fld.setText("" + (5 + (int)(Math.random() * ((25 - 5) + 1))));
        r_prod_sold_fld = new javax.swing.JTextField();
        r_prod_sold_fld.setText("" + (4 + (int)(Math.random() * ((14 - 4) + 1))));
        r_new_cust_fld = new javax.swing.JTextField();
        r_new_cust_fld.setText("" + (2 + (int)(Math.random() * ((6 - 2) + 1))));
        r_rev_fld = new javax.swing.JTextField();
        r_rev_fld.setText("" + formatter.format(r_rev));
        r_prof_fld = new javax.swing.JTextField();
        r_prof_fld.setText("" + formatter.format(r_rev - (2500 + (Math.random() * ((8000 - 2500 ) + 1)))));
        okay_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Online");

        jLabel2.setText("In-Store");

        jLabel3.setText("Orders Placed:");

        jLabel4.setText("Products Sold:");

        jLabel5.setText("Number of New Customers:");

        jLabel6.setText("Revenue:");

        jLabel7.setText("Profit:");

        jLabel8.setText("Orders Placed:");

        jLabel9.setText("Products Sold:");

        jLabel10.setText("Number of New Customers:");

        jLabel11.setText("Revenue:");

        jLabel12.setText("Profit:");

        l_ord_placed_fld.setEditable(false);
        l_ord_placed_fld.setColumns(1);

        l_prod_sold_fld.setEditable(false);
        l_prod_sold_fld.setColumns(1);

        l_new_cust_fld.setEditable(false);
        l_new_cust_fld.setColumns(1);

        l_rev_fld.setEditable(false);
        l_rev_fld.setColumns(1);

        l_prof_fld.setEditable(false);
        l_prof_fld.setColumns(1);

        r_ord_placed_fld.setEditable(false);
        r_ord_placed_fld.setColumns(1);

        r_prod_sold_fld.setEditable(false);
        r_prod_sold_fld.setColumns(1);

        r_new_cust_fld.setEditable(false);
        r_new_cust_fld.setColumns(1);

        r_rev_fld.setEditable(false);
        r_rev_fld.setColumns(1);

        r_prof_fld.setEditable(false);
        r_prof_fld.setColumns(1);

        okay_btn.setText("Okay");
        okay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_ord_placed_fld, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(l_prod_sold_fld)
                            .addComponent(l_prof_fld))
                        .addComponent(l_new_cust_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_rev_fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(r_rev_fld)
                    .addComponent(r_prof_fld)
                    .addComponent(r_new_cust_fld)
                    .addComponent(r_prod_sold_fld)
                    .addComponent(r_ord_placed_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okay_btn)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(l_ord_placed_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_ord_placed_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(l_prod_sold_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_prod_sold_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(l_new_cust_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_new_cust_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(l_rev_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_rev_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(l_prof_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_prof_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okay_btn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_btnActionPerformed
        dispose();
    }//GEN-LAST:event_okay_btnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField l_new_cust_fld;
    private javax.swing.JTextField l_ord_placed_fld;
    private javax.swing.JTextField l_prod_sold_fld;
    private javax.swing.JTextField l_prof_fld;
    private javax.swing.JTextField l_rev_fld;
    private javax.swing.JButton okay_btn;
    private javax.swing.JTextField r_new_cust_fld;
    private javax.swing.JTextField r_ord_placed_fld;
    private javax.swing.JTextField r_prod_sold_fld;
    private javax.swing.JTextField r_prof_fld;
    private javax.swing.JTextField r_rev_fld;
    // End of variables declaration//GEN-END:variables
}
