/*
 * @author Ethan Emmons
 */
public class ReportsMenu extends javax.swing.JFrame {
    public ReportsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monthly_sales_btn = new javax.swing.JButton();
        onlinevsinstore_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        monthly_sales_btn.setText("Monthly Sales");
        monthly_sales_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthly_sales_btnActionPerformed(evt);
            }
        });

        onlinevsinstore_btn.setText("Online vs. In-Store");
        onlinevsinstore_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlinevsinstore_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(monthly_sales_btn)
                .addGap(50, 50, 50)
                .addComponent(onlinevsinstore_btn)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthly_sales_btn)
                    .addComponent(onlinevsinstore_btn))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthly_sales_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthly_sales_btnActionPerformed
        MonthlySalesReport frame = new MonthlySalesReport();
        frame.setVisible(true);
    }//GEN-LAST:event_monthly_sales_btnActionPerformed

    private void onlinevsinstore_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlinevsinstore_btnActionPerformed
        OnlineVsInstoreReport frame = new OnlineVsInstoreReport();
        frame.setVisible(true);
    }//GEN-LAST:event_onlinevsinstore_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton monthly_sales_btn;
    private javax.swing.JButton onlinevsinstore_btn;
    // End of variables declaration//GEN-END:variables
}
