/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ethan - God Tier
 */
public class ViewUserAccountDetails extends javax.swing.JFrame {

    /**
     * Creates new form UserAccountDetails
     */
    private Customer cust;
    public ViewUserAccountDetails(Customer cust) {
        initComponents();
        this.cust = cust;
        cust_id.setText(cust.getId());
        cust_fname.setText(cust.getFname());
        cust_lname.setText(cust.getLname());
        cust_addr.setText(cust.getAddress());
        cust_join_date.setText(cust.getAddress());
        cust_phone.setText(cust.getPhone());
        cust_email.setText(cust.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cust_id_lbl = new javax.swing.JLabel();
        cust_fname_lbl = new javax.swing.JLabel();
        cust_lname_lbl = new javax.swing.JLabel();
        cust_addr_lbl = new javax.swing.JLabel();
        cust_join_date_lbl = new javax.swing.JLabel();
        cust_phone_lbl = new javax.swing.JLabel();
        cust_email_lbl = new javax.swing.JLabel();
        cust_id = new javax.swing.JTextField();
        cust_fname = new javax.swing.JTextField();
        cust_lname = new javax.swing.JTextField();
        cust_addr = new javax.swing.JTextField();
        cust_join_date = new javax.swing.JTextField();
        cust_phone = new javax.swing.JTextField();
        cust_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cust_id_lbl.setText("Customer ID");

        cust_fname_lbl.setText("First Name");

        cust_lname_lbl.setText("Last Name");

        cust_addr_lbl.setText("Address");
        cust_addr_lbl.setToolTipText("");

        cust_join_date_lbl.setText("Join Date");

        cust_phone_lbl.setText("Phone Number");

        cust_email_lbl.setText("Email");

        cust_id.setEditable(false);
        cust_id.setColumns(1);

        cust_fname.setEditable(false);
        cust_fname.setColumns(1);

        cust_lname.setEditable(false);
        cust_lname.setColumns(1);

        cust_addr.setEditable(false);
        cust_addr.setColumns(1);

        cust_join_date.setEditable(false);
        cust_join_date.setColumns(1);

        cust_phone.setEditable(false);
        cust_phone.setColumns(1);

        cust_email.setEditable(false);
        cust_email.setColumns(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cust_email_lbl)
                    .addComponent(cust_phone_lbl)
                    .addComponent(cust_join_date_lbl)
                    .addComponent(cust_addr_lbl)
                    .addComponent(cust_lname_lbl)
                    .addComponent(cust_fname_lbl)
                    .addComponent(cust_id_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cust_id, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cust_fname)
                    .addComponent(cust_lname)
                    .addComponent(cust_addr)
                    .addComponent(cust_join_date)
                    .addComponent(cust_phone)
                    .addComponent(cust_email))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_id_lbl)
                    .addComponent(cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_fname_lbl)
                    .addComponent(cust_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_lname_lbl)
                    .addComponent(cust_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_addr_lbl)
                    .addComponent(cust_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_join_date_lbl)
                    .addComponent(cust_join_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_phone_lbl)
                    .addComponent(cust_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cust_email_lbl)
                    .addComponent(cust_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewUserAccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewUserAccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewUserAccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewUserAccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewUserAccountDetails().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cust_addr;
    private javax.swing.JLabel cust_addr_lbl;
    private javax.swing.JTextField cust_email;
    private javax.swing.JLabel cust_email_lbl;
    private javax.swing.JTextField cust_fname;
    private javax.swing.JLabel cust_fname_lbl;
    private javax.swing.JTextField cust_id;
    private javax.swing.JLabel cust_id_lbl;
    private javax.swing.JTextField cust_join_date;
    private javax.swing.JLabel cust_join_date_lbl;
    private javax.swing.JTextField cust_lname;
    private javax.swing.JLabel cust_lname_lbl;
    private javax.swing.JTextField cust_phone;
    private javax.swing.JLabel cust_phone_lbl;
    // End of variables declaration//GEN-END:variables
}
