import javax.swing.DefaultListModel;

/*
 * @author Ethan Emmons
 */
public class ViewReturnRequests extends javax.swing.JFrame {
    private DefaultListModel ret_req_ids_dlm;
    
    public ViewReturnRequests() {
        ret_req_ids_dlm = new DefaultListModel();
        ret_req_ids_dlm.addElement("0001");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ret_req_ids_list = new javax.swing.JList(ret_req_ids_dlm);
        ret_req_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ret_id_fld = new javax.swing.JTextField();
        ord_id_fld = new javax.swing.JTextField();
        cust_id_fld = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ret_reason = new javax.swing.JTextArea();
        accept_btn = new javax.swing.JButton();
        deny_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ret_req_ids_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ret_req_ids_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ret_req_ids_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ret_req_ids_list);

        ret_req_lbl.setText("Return Requests:");

        jLabel1.setText("Return ID:");

        jLabel2.setText("Order ID:");

        jLabel3.setText("Customer ID:");

        jLabel4.setText("Reason for return:");

        ret_id_fld.setColumns(1);

        ord_id_fld.setColumns(1);

        cust_id_fld.setColumns(1);

        ret_reason.setEditable(false);
        ret_reason.setColumns(20);
        ret_reason.setLineWrap(true);
        ret_reason.setRows(5);
        ret_reason.setWrapStyleWord(true);
        jScrollPane2.setViewportView(ret_reason);

        accept_btn.setText("Accept");
        accept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_btnActionPerformed(evt);
            }
        });

        deny_btn.setText("Deny");
        deny_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deny_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(ret_req_lbl))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ret_id_fld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(ord_id_fld, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cust_id_fld, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(accept_btn)
                        .addGap(65, 65, 65)
                        .addComponent(deny_btn)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ret_req_lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ret_id_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ord_id_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cust_id_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deny_btn)
                    .addComponent(accept_btn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ret_req_ids_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ret_req_ids_listMouseClicked
        ret_req_ids_list.getSelectedValue();
        ord_id_fld.setText("0003");
        ret_id_fld.setText("0001");
        cust_id_fld.setText("0001");
        ret_reason.setText("The foam is very uncomfortable and I am affraid my lizard will eat it.");
    }//GEN-LAST:event_ret_req_ids_listMouseClicked

    private void accept_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_btnActionPerformed
        ret_req_ids_dlm.removeAllElements();
        ord_id_fld.setText("");
        ret_id_fld.setText("");
        cust_id_fld.setText("");
        ret_reason.setText("");
    }//GEN-LAST:event_accept_btnActionPerformed

    private void deny_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deny_btnActionPerformed
        ret_req_ids_dlm.removeAllElements();
        ord_id_fld.setText("");
        ret_id_fld.setText("");
        cust_id_fld.setText("");
        ret_reason.setText("");
    }//GEN-LAST:event_deny_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept_btn;
    private javax.swing.JTextField cust_id_fld;
    private javax.swing.JButton deny_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ord_id_fld;
    private javax.swing.JTextField ret_id_fld;
    private javax.swing.JTextArea ret_reason;
    private javax.swing.JList<String> ret_req_ids_list;
    private javax.swing.JLabel ret_req_lbl;
    // End of variables declaration//GEN-END:variables
}
